### ISSUE TITLE
Better Widget Font Scaling: Stop using hardcoded pixel values in the widgets

### ISSUE THREAD

**Issue by WildBunnie** [UA-Smart-Signage-Platform/Content-Manager-System-and-Content-Creator-Tool#155]
### Describe the feature

Currently some of the widgets use hardcoded pixel values, making it not work well with screens of different sizes.

### Use Case

The system already takes care of resizing the html for different screen sizes, so this is only logical.

### Proposed Solution

Use vw and vh instead of px.

**Comment by pdPinho** [comment]
solved in #159
