### ISSUE TITLE
Login: Update state management of login

### ISSUE THREAD

**Issue by fungame2270** [UA-Smart-Signage-Platform/Content-Manager-System-and-Content-Creator-Tool#181]
### Describe the feature

This issue aims to refactor the management of the jwt token and session on the frontend side of the application.

### Proposed Solution

Using the [zustand](https://zustand-demo.pmnd.rs/) library create a global state to manage the session on the browser and using the [TypeScript Cookie](https://github.com/carhartl/typescript-cookie#readme) create a Cookie to save the jwt token.

**Comment by pdPinho** [comment]
@fungame2270 Do not forget to create a description for this issue and then close it as it has been solved on #188
