### ISSUE TITLE
Monitors & Groups: Updating frontend so it works with backend

### ISSUE THREAD

**Issue by fungame2270** [UA-Smart-Signage-Platform/Content-Manager-System-and-Content-Creator-Tool#189]
### Describe the feature
Updating frontend to use react query and the new database.

### Proposed Solution
Update the code of the page Monitors and Groups from useEffects to fetch data to react query api.
Update Json management to be in conforms with the new database scheme.  

### Other Information
N/A

**Comment by pdPinho** [comment]
@fungame2270 Please follow the issue creation standard guide
