### ISSUE TITLE
Revamping some of the current File (Media) implementation

### ISSUE THREAD

**Issue by pdPinho** [UA-Smart-Signage-Platform/Content-Manager-System-and-Content-Creator-Tool#65]
The current implementation is missing the following:
- Logs
- Tests
- Some endpoints
- Maybe logic (?)

This is being a big bottleneck for frontend, therefore I'll be fixing this.

**Comment by DiogoSilva1904** [comment]
In this issue, integration tests have also been implemented, complete with the necessary setup for utilizing test containers.
